#!/usr/bin/env bash
set -euo pipefail

ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
hwclock --systohc

sed -i '/en_GB.UTF-8/s/^#//' /etc/locale.gen
locale-gen
echo "LANG=en_GB.UTF-8" >> /etc/locale.conf

echo "CrescentLibrary" >> /etc/hostname

passwd

read -p "Enter a username: " username && sudo useradd -m -g users -G wheel "$username"
passwd "$username"
echo "$username ALL=(ALL) ALL" >> /etc/sudoers.d/"$username"
