#!/usr/bin/env bash
set -euo pipefail

sed -i '/^MODULES=/c\MODULES=(btrfs)' /etc/mkinitcpio.conf
sed -i '/^HOOKS=/c\HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt filesystems resume fsck)'/etc/mkinitcpio.conf

mkinitcpio -P
